import { CaptionItem, CaptionStyle, CaptionWord } from './store';

export interface AssOptions {
  title?: string;
  width?: number; // default 1080
  height?: number; // default 1920
  aspectRatio?: '9:16' | '16:9' | '1:1';
}

/**
 * Convert Hex color string to ASS Color format: &HAABBGGRR (Hex Alpha, Blue, Green, Red)
 * Note: In ASS, Alpha 00 is fully opaque, FF is fully transparent.
 */
export function hexToAssColor(hex: string, opacityPercent: number = 100): string {
  if (!hex) return '&H00FFFFFF';
  let cleanHex = hex.replace('#', '').trim();
  if (cleanHex.length === 3) {
    cleanHex = cleanHex.split('').map((c) => c + c).join('');
  }
  if (cleanHex.length < 6) return '&H00FFFFFF';

  const rr = cleanHex.substring(0, 2).toUpperCase();
  const gg = cleanHex.substring(2, 4).toUpperCase();
  const bb = cleanHex.substring(4, 6).toUpperCase();

  // Alpha in ASS: 00 = 100% visible (opaque), FF = 0% visible (transparent)
  const alphaVal = Math.round(255 * (1 - Math.max(0, Math.min(100, opacityPercent)) / 100));
  const aa = alphaVal.toString(16).padStart(2, '0').toUpperCase();

  return `&H${aa}${bb}${gg}${rr}`;
}

/**
 * Format seconds as ASS timestamp: H:MM:SS.cc (centiseconds)
 */
export function formatAssTime(seconds: number): string {
  if (isNaN(seconds) || seconds < 0) seconds = 0;
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);

  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

/**
 * Generate Advanced SubStation Alpha (.ass) subtitle file content
 */
export function generateAss(
  captions: CaptionItem[],
  style: CaptionStyle,
  options: AssOptions = {}
): string {
  const title = options.title || 'SUBTHAITLE Subtitle';
  let width = options.width || 1080;
  let height = options.height || 1920;

  if (options.aspectRatio === '16:9') {
    width = 1920;
    height = 1080;
  } else if (options.aspectRatio === '1:1') {
    width = 1080;
    height = 1080;
  }

  // Typography properties
  const fontName = style.fontFamily || 'Noto Sans Thai';
  // Scale font size proportionally for 1080p canvas (base preview font is 18-48px)
  const fontSize = Math.round(style.fontSize * 2.4);
  const primaryColor = hexToAssColor(style.textColor || '#FFFFFF', 100);
  const secondaryColor = hexToAssColor(style.highlightColor || '#FACC15', 100);
  const outlineColor = style.hasOutline
    ? hexToAssColor(style.outlineColor || '#000000', 100)
    : '&H00000000';
  const shadowColor = style.hasShadow
    ? hexToAssColor(style.shadowColor || '#000000', (style.shadowOpacity ?? 0.8) * 100)
    : '&H00000000';
  const backColor = style.hasBackground
    ? hexToAssColor(style.backgroundColor || '#000000', style.backgroundOpacity ?? 70)
    : '&H00000000';

  const isBold = style.fontWeight === 'bold' || style.fontWeight === '700' || style.fontWeight === '800' ? -1 : 0;
  const outlineWidth = style.hasOutline ? Math.round((style.outlineWidth || 3) * 1.8) : 0;
  const shadowDepth = style.hasShadow ? Math.round((style.shadowBlur || 8) * 0.4) : 0;

  // Alignment: NumPad layout (1=Bottom Left, 2=Bottom Center, 3=Bottom Right)
  const alignment = style.textAlign === 'left' ? 1 : style.textAlign === 'right' ? 3 : 2;

  // Margin calculation
  const marginV = Math.round(((style.positionY ?? 15) / 100) * height);
  const maxWidthPct = style.maxWidth ?? 92;
  const sideMargin = Math.round(((100 - maxWidthPct) / 200) * width);
  const marginL = sideMargin;
  const marginR = sideMargin;
  const spacing = Math.round((style.letterSpacing ?? 0) * 1.5);

  let ass = `[Script Info]
; Script generated by SUBTHAITLE Studio
Title: ${title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: ${width}
PlayResY: ${height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontName},${fontSize},${primaryColor},${secondaryColor},${outlineColor},${style.hasBackground ? backColor : shadowColor},${isBold},0,0,0,100,100,${spacing},0,${style.hasBackground ? 3 : 1},${outlineWidth},${shadowDepth},${alignment},${marginL},${marginR},${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  captions.forEach((cue) => {
    const startStr = formatAssTime(cue.start);
    const endStr = formatAssTime(cue.end);

    let textContent = '';

    if (style.enableWordHighlight && cue.words && cue.words.length > 0) {
      // Build Karaoke highlighted text tags (\k<duration_in_centiseconds>)
      let lineBuilt = '';
      cue.words.forEach((w: CaptionWord) => {
        if (!w.word) return;
        const durationCs = Math.max(1, Math.round((w.end - w.start) * 100));
        lineBuilt += `{\\k${durationCs}}${w.word}`;
      });
      textContent = lineBuilt || cue.text;
    } else {
      textContent = cue.text.replace(/\n/g, '\\N');
    }

    ass += `Dialogue: 0,${startStr},${endStr},Default,,0,0,0,,${textContent}\n`;
  });

  return ass;
}

/**
 * Trigger browser file download for .ass file
 */
export function downloadAss(
  captions: CaptionItem[],
  style: CaptionStyle,
  filename: string = 'subtitles.ass',
  options: AssOptions = {}
): void {
  const assContent = generateAss(captions, style, {
    title: filename.replace(/\.ass$/i, ''),
    ...options,
  });

  const blob = new Blob([assContent], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename.endsWith('.ass') ? filename : `${filename}.ass`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
