import { CaptionStyle } from './store';

export interface StylePreset {
  id: string;
  name: string;
  description: string;
  previewBg: string;
  previewTextColor: string;
  previewHighlightColor: string;
  style: CaptionStyle;
}

export const SUBTITLE_PRESETS: StylePreset[] = [
  {
    id: 'tiktok-viral',
    name: '🔥 TikTok Viral (ฮิตสุด)',
    description: 'ฟอนต์ Kanit หนาพิเศษ ขอบดำคมกริบ ไฮไลท์เหลืองนีออนสะดุดตา',
    previewBg: 'bg-zinc-900',
    previewTextColor: '#FFFFFF',
    previewHighlightColor: '#FACC15',
    style: {
      fontFamily: 'Kanit',
      fontSize: 34,
      textColor: '#FFFFFF',
      fontWeight: '800',
      letterSpacing: 0,
      lineHeight: 1.4,
      positionY: 18,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 92,
      hasShadow: true,
      shadowColor: '#000000',
      shadowBlur: 10,
      shadowOpacity: 0.9,
      hasOutline: true,
      outlineColor: '#000000',
      outlineWidth: 3,
      enableWordHighlight: true,
      highlightColor: '#FACC15', // Neon Yellow
      hasBackground: false,
      backgroundColor: '#000000',
      backgroundOpacity: 65,
    },
  },
  {
    id: 'orange-creator',
    name: '🟠 Creator Orange (คุมโทน)',
    description: 'ฟอนต์ Prompt ตัวหนา ไฮไลท์สีส้มสดใส สไตล์สตูดิโอครีเอเตอร์',
    previewBg: 'bg-zinc-900',
    previewTextColor: '#FFFFFF',
    previewHighlightColor: '#FB923C',
    style: {
      fontFamily: 'Prompt',
      fontSize: 32,
      textColor: '#FFFFFF',
      fontWeight: '700',
      letterSpacing: 0.5,
      lineHeight: 1.4,
      positionY: 16,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 92,
      hasShadow: true,
      shadowColor: '#000000',
      shadowBlur: 8,
      shadowOpacity: 0.85,
      hasOutline: true,
      outlineColor: '#000000',
      outlineWidth: 3,
      enableWordHighlight: true,
      highlightColor: '#FB923C', // Vibrant Orange
      hasBackground: false,
      backgroundColor: '#000000',
      backgroundOpacity: 70,
    },
  },
  {
    id: 'minimal-cinema',
    name: '🎬 Minimalist Box (มินิมอลกล่องดำ)',
    description: 'มีแถบพื้นหลังสีดำโปร่งใส อ่านง่ายบนทุกฉาก ทุกวิดีโอ',
    previewBg: 'bg-zinc-800',
    previewTextColor: '#FFFFFF',
    previewHighlightColor: '#38BDF8',
    style: {
      fontFamily: 'Noto Sans Thai',
      fontSize: 16,
      textColor: '#FFFFFF',
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 1.4,
      positionY: 14,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 90,
      hasShadow: false,
      shadowColor: '#000000',
      shadowBlur: 4,
      shadowOpacity: 0.5,
      hasOutline: false,
      outlineColor: '#000000',
      outlineWidth: 0,
      enableWordHighlight: true,
      highlightColor: '#38BDF8', // Cyan Sky
      hasBackground: true,
      backgroundColor: '#000000',
      backgroundOpacity: 75,
    },
  },
  {
    id: 'youtube-clean',
    name: '📺 YouTube Vlog (คลีนสะอาดตา)',
    description: 'ฟอนต์ Sarabun คมชัด เงาเบาๆ สไตล์คลิปสอน สัมภาษณ์ และสารคดี',
    previewBg: 'bg-zinc-900',
    previewTextColor: '#FFFFFF',
    previewHighlightColor: '#4ADE80',
    style: {
      fontFamily: 'Sarabun',
      fontSize: 22,
      textColor: '#FFFFFF',
      fontWeight: '700',
      letterSpacing: 0,
      lineHeight: 1.5,
      positionY: 12,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 92,
      hasShadow: true,
      shadowColor: '#000000',
      shadowBlur: 6,
      shadowOpacity: 0.8,
      hasOutline: true,
      outlineColor: '#000000',
      outlineWidth: 2,
      enableWordHighlight: true,
      highlightColor: '#4ADE80', // Mint Green
      hasBackground: false,
      backgroundColor: '#000000',
      backgroundOpacity: 60,
    },
  },
  {
    id: 'cyber-neon',
    name: '⚡ Cyberpunk Neon (นีออนล้ำๆ)',
    description: 'ฟอนต์ Chonburi ตัวหนา ไฮไลท์ชมพูนีออนสไตล์เกมมิ่งและ Gadget',
    previewBg: 'bg-zinc-950',
    previewTextColor: '#E0F2FE',
    previewHighlightColor: '#F43F5E',
    style: {
      fontFamily: 'Chonburi',
      fontSize: 34,
      textColor: '#E0F2FE',
      fontWeight: '700',
      letterSpacing: 1,
      lineHeight: 1.4,
      positionY: 18,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 92,
      hasShadow: true,
      shadowColor: '#0369A1',
      shadowBlur: 14,
      shadowOpacity: 0.95,
      hasOutline: true,
      outlineColor: '#020617',
      outlineWidth: 3,
      enableWordHighlight: true,
      highlightColor: '#F43F5E', // Neon Rose
      hasBackground: false,
      backgroundColor: '#020617',
      backgroundOpacity: 80,
    },
  },
  {
    id: 'mrbeast-bold',
    name: '⚡ MrBeast Punch (กระแทกตา)',
    description: 'ฟอนต์ตัวหนาพิเศษ ไฮไลท์สีเขียวสะท้อนแสง สไตล์คลิปไวรัลความยาวสั้น',
    previewBg: 'bg-zinc-950',
    previewTextColor: '#FFFFFF',
    previewHighlightColor: '#22C55E',
    style: {
      fontFamily: 'Kanit',
      fontSize: 36,
      textColor: '#FFFFFF',
      fontWeight: '800',
      letterSpacing: 0.5,
      lineHeight: 1.3,
      positionY: 20,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 88,
      hasShadow: true,
      shadowColor: '#000000',
      shadowBlur: 12,
      shadowOpacity: 0.95,
      hasOutline: true,
      outlineColor: '#000000',
      outlineWidth: 4,
      enableWordHighlight: true,
      highlightColor: '#22C55E', // Electric Lime
      hasBackground: false,
      backgroundColor: '#000000',
      backgroundOpacity: 70,
    },
  },
  {
    id: 'luxury-gold',
    name: '✨ Luxury & Gold (พรีเมียมหรูหรา)',
    description: 'ฟอนต์ Serif ไฮไลท์สีทองคำแชมเปญ สำหรับรีวิวบ้านหรู อสังหาฯ และแบรนด์เนม',
    previewBg: 'bg-stone-950',
    previewTextColor: '#FEF08A',
    previewHighlightColor: '#EAB308',
    style: {
      fontFamily: 'Mitr',
      fontSize: 24,
      textColor: '#FEF08A',
      fontWeight: '600',
      letterSpacing: 1.5,
      lineHeight: 1.5,
      positionY: 15,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 85,
      hasShadow: true,
      shadowColor: '#713F12',
      shadowBlur: 10,
      shadowOpacity: 0.8,
      hasOutline: true,
      outlineColor: '#451A03',
      outlineWidth: 1,
      enableWordHighlight: true,
      highlightColor: '#EAB308', // Gold
      hasBackground: true,
      backgroundColor: '#1C1917',
      backgroundOpacity: 60,
    },
  },
  {
    id: 'comic-boom',
    name: '💥 Comic & Anime (การ์ตูนป๊อป)',
    description: 'สไตล์การ์ตูนสดใส เส้นขอบหนาเตอะ ไฮไลท์สีฟ้าสว่าง สำหรับสายแคสเกมและรีแอค',
    previewBg: 'bg-zinc-900',
    previewTextColor: '#FFFFFF',
    previewHighlightColor: '#06B6D4',
    style: {
      fontFamily: 'Prompt',
      fontSize: 32,
      textColor: '#FFFFFF',
      fontWeight: '800',
      letterSpacing: 0,
      lineHeight: 1.4,
      positionY: 18,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 90,
      hasShadow: true,
      shadowColor: '#083344',
      shadowBlur: 8,
      shadowOpacity: 0.9,
      hasOutline: true,
      outlineColor: '#082F49',
      outlineWidth: 3,
      enableWordHighlight: true,
      highlightColor: '#06B6D4', // Vibrant Cyan
      hasBackground: false,
      backgroundColor: '#000000',
      backgroundOpacity: 60,
    },
  },
  {
    id: 'retro-vhs',
    name: '📼 Retro VHS 90s (วินเทจคลาสสิก)',
    description: 'ฟอนต์สไตล์ม้วนเทปยุค 90s พร้อมขอบเงาสีเข้ม สำหรับคลิปฟีลย้อนยุคและสารคดี',
    previewBg: 'bg-slate-950',
    previewTextColor: '#FEF9C3',
    previewHighlightColor: '#F59E0B',
    style: {
      fontFamily: 'Sarabun',
      fontSize: 22,
      textColor: '#FEF9C3',
      fontWeight: '700',
      letterSpacing: 1.2,
      lineHeight: 1.4,
      positionY: 12,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 88,
      hasShadow: true,
      shadowColor: '#451A03',
      shadowBlur: 6,
      shadowOpacity: 0.85,
      hasOutline: true,
      outlineColor: '#1E293B',
      outlineWidth: 2,
      enableWordHighlight: true,
      highlightColor: '#F59E0B', // Retro Amber
      hasBackground: true,
      backgroundColor: '#0F172A',
      backgroundOpacity: 75,
    },
  },
  {
    id: 'pastel-story',
    name: '🌸 Pastel Story (พาสเทลน่ารัก)',
    description: 'โทนสีละมุน นุ่มนวลตา ไฮไลท์สีชมพูพีช สำหรับคลิป Lifestyle, Daily Vlog และคาเฟ่',
    previewBg: 'bg-zinc-900',
    previewTextColor: '#FFF1F2',
    previewHighlightColor: '#FB7185',
    style: {
      fontFamily: 'Mitr',
      fontSize: 26,
      textColor: '#FFF1F2',
      fontWeight: '600',
      letterSpacing: 0.5,
      lineHeight: 1.4,
      positionY: 15,
      positionX: 50,
      textAlign: 'center',
      maxWidth: 90,
      hasShadow: true,
      shadowColor: '#881337',
      shadowBlur: 6,
      shadowOpacity: 0.7,
      hasOutline: true,
      outlineColor: '#4C0519',
      outlineWidth: 1,
      enableWordHighlight: true,
      highlightColor: '#FB7185', // Pastel Rose
      hasBackground: true,
      backgroundColor: '#27272A',
      backgroundOpacity: 65,
    },
  },
];
